# Generated by Django 4.2.3 on 2023-08-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_yogaasana"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YogaAsana",
        ),
    ]
