# Generated by Django 4.2.3 on 2023-08-08 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_squatrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curlrecord",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="squatrecord",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="curlrecord",
            name="date",
            field=models.DateField(default=datetime.date(2023, 8, 8)),
        ),
        migrations.AddField(
            model_name="squatrecord",
            name="date",
            field=models.DateField(default=datetime.date(2023, 8, 8)),
        ),
    ]
