# Generated by Django 4.2.3 on 2023-08-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_curlrecord_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AasnaVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("is_aasana_done", models.BooleanField(default=False)),
            ],
        ),
    ]
