# Generated by Django 4.2.3 on 2023-08-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_curlrecord_date_alter_squatrecord_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="aasnavideo",
            name="caloriesburn",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
