# Generated by Django 4.2.3 on 2023-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_fitnessprofile_yogaasanarecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
