# Generated by Django 4.2.3 on 2023-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_registereduser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curlrecord",
            name="curls_done",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
