# Generated by Django 4.2.3 on 2023-08-09 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_squatrecord_squats_done"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pushups_done", models.PositiveIntegerField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.registereduser",
                    ),
                ),
            ],
        ),
    ]
