# Generated by Django 4.2.3 on 2023-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_pushuprecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yogaasanarecord",
            name="aasna",
            field=models.CharField(default="", max_length=400),
        ),
    ]
