# Generated by Django 4.2.3 on 2023-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_yogaasanarecord_calories_burnt"),
    ]

    operations = [
        migrations.AddField(
            model_name="yogaasanarecord",
            name="times",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
